### PR TITLE
Fix issue check key array file upload

### PR DESCRIPTION
**Pull request by nhatcodemenschen**
Fix error:
<b>Notice</b>:  Undefined index: file-2 in <b>/home/tccschwe/public_html/wp-content/plugins/contact-form-cfdb7/contact-form-cfdb-7.php</b> on line <b>164</b><br />
{"into":"#wpcf7-f280-o1","status":"mail_sent","message":"Vielen Dank f\u00fcr Ihre Nachricht. Sie wurde erfolgreich gesendet.","posted_data_hash":"653e8f25e899b3e98ac5a26e53ea6ff6"}

Screenshot: https://ibb.co/2SXZtTz

Thanks

### CODE REVIEW

**Comment by arshidkv12** [comment]
How to generate error?

**Comment by nhatcodemenschen** [comment]
https://ibb.co/KG6dXLW
https://ibb.co/d4DnyJD

When form contact you have use field Field. So then submit I see that have error.

**Comment by arshidkv12** [comment]
Please try without any other third party file upload contact form 7 plugins.

**Comment by nhatcodemenschen** [comment]
Can you help me try that? I leave my company now, thank

**Pull request closed without merging**
